<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ApplicationIcon>PowerSA.ico</ApplicationIcon>
    <AssemblyName>PowerSA-B2B-Setup</AssemblyName>
    <RootNamespace>PowerSA.B2B.Setup</RootNamespace>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="PowerSA.ico" LogicalName="PowerSA.ico" />
  </ItemGroup>
</Project>
