/*
  Rebuild Logo customer total tables from LG_003_01_CLFLINE.

  Why this exists:
  Logo's Cari Hesaplar list reads customer balances from derived total tables.
  When LG_003_01_CLTOTFIL and LG_003_01_GNTOTCL are empty, customer movements can
  exist in CLFLINE while the Logo customer list still shows blank balances.

  Scope:
  - Rebuilds LG_003_01_CLTOTFIL and LG_003_01_GNTOTCL for customers with active
    CLFLINE rows.
  - Does not create, update, or delete any customer movement.
  - Ignores cancelled rows.
*/

SET NOCOUNT ON;
SET XACT_ABORT ON;

IF OBJECT_ID(N'dbo.LG_003_01_CLFLINE', N'U') IS NULL
   OR OBJECT_ID(N'dbo.LG_003_01_CLTOTFIL', N'U') IS NULL
   OR OBJECT_ID(N'dbo.LG_003_01_GNTOTCL', N'U') IS NULL
BEGIN
    RAISERROR('Required Logo customer balance tables were not found.', 16, 1);
    RETURN;
END;

IF COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'CARDREF') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'TOTTYP') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'MONTH_') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'DEBIT') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'CREDIT') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'YEAR_') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'BRANCH') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_CLTOTFIL', N'DEPARTMENT') IS NULL
BEGIN
    RAISERROR('LG_003_01_CLTOTFIL schema is not compatible with this rebuild script.', 16, 1);
    RETURN;
END;

IF COL_LENGTH(N'dbo.LG_003_01_GNTOTCL', N'CARDREF') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_GNTOTCL', N'TOTTYP') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_GNTOTCL', N'DEBIT') IS NULL
   OR COL_LENGTH(N'dbo.LG_003_01_GNTOTCL', N'CREDIT') IS NULL
BEGIN
    RAISERROR('LG_003_01_GNTOTCL schema is not compatible with this rebuild script.', 16, 1);
    RETURN;
END;

IF OBJECT_ID('tempdb..#CustomerRefs') IS NOT NULL
BEGIN
    DROP TABLE #CustomerRefs;
END;

SELECT DISTINCT CLIENTREF AS CARDREF
INTO #CustomerRefs
FROM dbo.LG_003_01_CLFLINE WITH (NOLOCK)
WHERE ISNULL(CLIENTREF, 0) > 0;

BEGIN TRANSACTION;

DELETE totals
FROM dbo.LG_003_01_CLTOTFIL AS totals
INNER JOIN #CustomerRefs AS customers
    ON customers.CARDREF = totals.CARDREF;

DELETE totals
FROM dbo.LG_003_01_GNTOTCL AS totals
INNER JOIN #CustomerRefs AS customers
    ON customers.CARDREF = totals.CARDREF;

;WITH SourceRows AS (
    SELECT
        CLIENTREF AS CARDREF,
        DATE_,
        ISNULL(SIGN, 0) AS SIGN,
        COALESCE(TRNET, AMOUNT, 0) AS LOCALNET,
        COALESCE(REPORTNET, TRNET, AMOUNT, 0) AS REPORTNET,
        ISNULL(BRANCH, 0) AS BRANCH,
        ISNULL(DEPARTMENT, 0) AS DEPARTMENT
    FROM dbo.LG_003_01_CLFLINE WITH (NOLOCK)
    WHERE ISNULL(CLIENTREF, 0) > 0
      AND ISNULL(CANCELLED, 0) = 0
),
MonthlyLocal AS (
    SELECT
        CARDREF,
        CONVERT(SMALLINT, 1) AS TOTTYP,
        MONTH(DATE_) AS MONTH_,
        SUM(CASE WHEN SIGN = 0 THEN LOCALNET ELSE 0 END) AS DEBIT,
        SUM(CASE WHEN SIGN = 0 THEN 0 ELSE LOCALNET END) AS CREDIT,
        YEAR(DATE_) AS YEAR_,
        BRANCH,
        DEPARTMENT
    FROM SourceRows
    WHERE ABS(LOCALNET) > 0.0000001
    GROUP BY CARDREF, YEAR(DATE_), MONTH(DATE_), BRANCH, DEPARTMENT
),
MonthlyReport AS (
    SELECT
        CARDREF,
        CONVERT(SMALLINT, 2) AS TOTTYP,
        MONTH(DATE_) AS MONTH_,
        SUM(CASE WHEN SIGN = 0 THEN REPORTNET ELSE 0 END) AS DEBIT,
        SUM(CASE WHEN SIGN = 0 THEN 0 ELSE REPORTNET END) AS CREDIT,
        YEAR(DATE_) AS YEAR_,
        BRANCH,
        DEPARTMENT
    FROM SourceRows
    WHERE ABS(REPORTNET) > 0.0000001
    GROUP BY CARDREF, YEAR(DATE_), MONTH(DATE_), BRANCH, DEPARTMENT
),
MonthlyTotals AS (
    SELECT * FROM MonthlyLocal
    UNION ALL
    SELECT * FROM MonthlyReport
)
INSERT INTO dbo.LG_003_01_CLTOTFIL
    (CARDREF, TOTTYP, MONTH_, DEBIT, CREDIT, YEAR_, BRANCH, DEPARTMENT)
SELECT
    CARDREF,
    TOTTYP,
    MONTH_,
    SUM(DEBIT) AS DEBIT,
    SUM(CREDIT) AS CREDIT,
    YEAR_,
    BRANCH,
    DEPARTMENT
FROM MonthlyTotals
GROUP BY CARDREF, TOTTYP, MONTH_, YEAR_, BRANCH, DEPARTMENT
HAVING ABS(SUM(DEBIT)) > 0.0000001
    OR ABS(SUM(CREDIT)) > 0.0000001;

;WITH SourceRows AS (
    SELECT
        CLIENTREF AS CARDREF,
        ISNULL(SIGN, 0) AS SIGN,
        COALESCE(TRNET, AMOUNT, 0) AS LOCALNET,
        COALESCE(REPORTNET, TRNET, AMOUNT, 0) AS REPORTNET
    FROM dbo.LG_003_01_CLFLINE WITH (NOLOCK)
    WHERE ISNULL(CLIENTREF, 0) > 0
      AND ISNULL(CANCELLED, 0) = 0
),
GeneralLocal AS (
    SELECT
        CARDREF,
        CONVERT(SMALLINT, 1) AS TOTTYP,
        SUM(CASE WHEN SIGN = 0 THEN LOCALNET ELSE 0 END) AS DEBIT,
        SUM(CASE WHEN SIGN = 0 THEN 0 ELSE LOCALNET END) AS CREDIT
    FROM SourceRows
    WHERE ABS(LOCALNET) > 0.0000001
    GROUP BY CARDREF
),
GeneralReport AS (
    SELECT
        CARDREF,
        CONVERT(SMALLINT, 2) AS TOTTYP,
        SUM(CASE WHEN SIGN = 0 THEN REPORTNET ELSE 0 END) AS DEBIT,
        SUM(CASE WHEN SIGN = 0 THEN 0 ELSE REPORTNET END) AS CREDIT
    FROM SourceRows
    WHERE ABS(REPORTNET) > 0.0000001
    GROUP BY CARDREF
),
GeneralTotals AS (
    SELECT * FROM GeneralLocal
    UNION ALL
    SELECT * FROM GeneralReport
)
INSERT INTO dbo.LG_003_01_GNTOTCL
    (CARDREF, TOTTYP, DEBIT, CREDIT)
SELECT
    CARDREF,
    TOTTYP,
    SUM(DEBIT) AS DEBIT,
    SUM(CREDIT) AS CREDIT
FROM GeneralTotals
GROUP BY CARDREF, TOTTYP
HAVING ABS(SUM(DEBIT)) > 0.0000001
    OR ABS(SUM(CREDIT)) > 0.0000001;

DECLARE @CustomerCount INT = (SELECT COUNT(*) FROM #CustomerRefs);
DECLARE @MonthlyTotalRows INT = (SELECT COUNT(*) FROM dbo.LG_003_01_CLTOTFIL WHERE CARDREF IN (SELECT CARDREF FROM #CustomerRefs));
DECLARE @GeneralTotalRows INT = (SELECT COUNT(*) FROM dbo.LG_003_01_GNTOTCL WHERE CARDREF IN (SELECT CARDREF FROM #CustomerRefs));

COMMIT TRANSACTION;

SELECT
    @CustomerCount AS rebuilt_customer_count,
    @MonthlyTotalRows AS rebuilt_cltotfil_rows,
    @GeneralTotalRows AS rebuilt_gntotcl_rows;
